# -*- coding: utf-8 -*-
"""Regression_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MsAIiuH4tKHWtJ0jGscZq_5VZdsvkqMI
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Advertising.csv")

df.head()

df.info()

df.describe()

df[df['sales'] == df['sales'].max()]

df[df['sales'] == df['sales'].min()]

df.corr()['sales'][:-1]

fig,axes = plt.subplots(nrows=1,ncols=3,figsize=(16,6))

axes[0].plot(df['TV'],df['sales'],'o')
axes[0].set_ylabel("Sales")
axes[0].set_title("TV Spend")

axes[1].plot(df['radio'],df['sales'],'o')
axes[1].set_title("Radio Spend")
axes[1].set_ylabel("Sales")

axes[2].plot(df['newspaper'],df['sales'],'o')
axes[2].set_title("Newspaper Spend");
axes[2].set_ylabel("Sales")
plt.tight_layout();

X = df.drop('sales',axis=1)
y = df['sales']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)
test_predictions = model.predict(X_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error

MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

print(f'MAE : {MAE}')
print(f'MSE : {MSE}')
print(f'RMSE : {RMSE}')
print(f'Sales mean : {y.mean()}')

coeff_df = pd.DataFrame(model.coef_,X.columns,columns=['Coefficient'])
coeff_df

